### ISSUE TITLE
Implement operator + for Series

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/sdc#234]
With HPAT_CONFIG_PIPELINE_HPAT=0 the old test hpat.tests.test_series.TestSeries.test_series_sum2 do not work:
```
No definition for lowering <built-in function add>(series(float64, array(float64, 1d, C), none, False), series(float64, array(float64, 1d, C), none, False)) -> series(float64, array(float64, 1d, C), none, False)

File "hpat\tests\test_series.py", line 859:
        def test_impl(S):
            return (S + S).sum()
            ^

[1] During: lowering "$0.3 = S + S" at c:\Users\spokhode\Documents\hpat-workspace\hpat\hpat\tests\test_series.py (859)
```
As I can understand `add` operator for Series is not implemented yet.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/hpat/pull/203#issuecomment-539889035_

**Comment by kozlov-alexey** [comment]
@PokhodenkoSA Can we close this (as it should work already)?

**Comment by PokhodenkoSA** [comment]
Sure.
