### ISSUE TITLE
TypingError in read_csv()

### ISSUE THREAD

**Issue by akharche** [IntelPython/sdc#941]
TypingError: Cannot infer resulting DataFrame from constant file or parameters.

```
@numba.njit(parallel=True)
def foo(dpath):
  df=pd.read_csv(dpath)
  print(df.head())
```

**Comment by ashokei** [comment]
happens with intel python 3.7 and sdc 0.37.

> 

    >>> read_csv(unicode_type)                                               
                                                                                                
    There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'sdc_pandas_read_csv': File: sdc/datatypes/hpat_pandas_functions.py: Line 79.
        With argument(s): '(unicode_type)':
       Rejected as the implementation raised a specific error:                      
         TypingError: Cannot infer resulting DataFrame from constant file or parameters.            
      raised from /lib/python3.7/site-packages/sdc/datatypes/hpat_pandas_functions.py:227

**Comment by kozlov-alexey** [comment]
@ashokei Yes, actually, above usage of read_csv with non-constant file name (or other parameters defining resulting DF column types) is currently unsupported. But this is something we want to support in the future, so I've marked this as a feature request. But before that please use constant file names as argument of `read_csv` in the jitted function. 
You can refer to the documentation for more details: 
https://intelpython.github.io/sdc-doc/latest/_api_ref/pandas.read_csv.html#limitations
